### PR TITLE
Make #pop threadsafe

### LINKED ISSUE #7: Race condition on pop
I may be wrong but it seems like the following code has a potential race condition:

```rb
    safe_open 'r' do |file|
      value = file.gets @delimiter
      rest = file.read
    end
    safe_open 'w+' do |file|
      file.write rest
    end
```

e.g:

A obtains lock; A reads line; A caches rest
B obtains lock; B reads line; B caches rest
B obtains lock; B writes rest
A obtains lock; A writes rest

Fixed by not releasing the lock until `rest` is written back to the file:

```rb
FileQueue.class_eval do
  def pop
    value = nil
    safe_open 'r+' do |file|
      value = file.gets @delimiter
      rest = file.read
      file.rewind
      file.truncate(0)
      file.write(rest)
    end
    value ? value[0..-(@delimiter.length) - 1] : nil
  end
end
```

### PR DESCRIPTION
**Pull request by jbodah**
Fixes #7

### CODE REVIEW

**Comment by jbodah** [comment]
@pezra let me know what you think

**Review by pezra — APPROVED** [review]
**So** much better! 

Can you change the [Travis config to allow failures in jruby and rbx?](https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail) Once that is done I'll move this.

**Comment by pezra** [comment]
Two of the tests failed with lock acquisition timeout. I reran those tests but that result worries me a bit.

**Comment by pezra** [comment]
released as 1.0.0. thanks for the improvement.

**Comment by pezra** [comment]
make that 1.0.3. i had a couple of problems with the release script. 😄

**Pull request merged**
